spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/auth_test?autoReconnect=true&useSSL=false
    username: ${AUTH_DB_PWD:simu}
    password: ${AUTH_DB_USER:simu123}
    type: com.zaxxer.hikari.HikariDataSource

############################# Redis config #############################
cache:
  # pool config
  pool:
    maxIdle: 15
    maxTotal: 30
    maxWaitMillis: 6000
    minIdle: 1
    numTestsPerEvictionRun: 10
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 6000
  # enable redis
  redis:
    enabled: true
# if flush all the cache when start up
redis:
  database: 0
  host:
    address: ${REDIS_ADDRESS:116.62.146.35}
    password: ${REDIS_PWD:}
    port: ${REDIS_PORT:7000}
  setup:
    flushdb: true

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

